// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AnimationController from "./animation_controller"
application.register("animation", AnimationController)

import CalendarController from "./calendar_controller"
application.register("calendar", CalendarController)

import DiaryEditorController from "./diary_editor_controller"
application.register("diary-editor", DiaryEditorController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ImagePreviewController from "./image_preview_controller"
application.register("image-preview", ImagePreviewController)

import MessageController from "./message_controller"
application.register("message", MessageController)

import WaitingResponseController from "./waiting_response_controller"
application.register("waiting-response", WaitingResponseController)
