// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DiaryEditorController from "./diary_editor_controller"
application.register("diary-editor", DiaryEditorController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MessageController from "./message_controller"
application.register("message", MessageController)
